"""create labels, friendships and association tables

Revision ID: 526e9957529d
Revises: df5ddbe01935
Create Date: 2026-07-27 23:37:39.661837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '526e9957529d'
down_revision: Union[str, Sequence[str], None] = 'df5ddbe01935'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friendships',
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('addressee_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', name='friendshipstatus'), nullable=False),
    sa.CheckConstraint('requester_id <> addressee_id', name='ck_friendships_no_self_friendship'),
    sa.ForeignKeyConstraint(['addressee_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('requester_id', 'addressee_id')
    )
    op.create_index(op.f('ix_friendships_status'), 'friendships', ['status'], unique=False)
    op.create_table('labels',
    sa.Column('label_id', sa.Integer(), nullable=False),
    sa.Column('label_name', sa.String(length=50), nullable=False),
    sa.Column('label_color', sa.String(length=7), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('label_id')
    )
    op.create_index(op.f('ix_labels_label_name'), 'labels', ['label_name'], unique=False)
    op.create_index(op.f('ix_labels_user_id'), 'labels', ['user_id'], unique=False)
    op.create_table('blocking_tasks',
    sa.Column('blocking_task_id', sa.Integer(), nullable=False),
    sa.Column('blocked_task_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('blocking_task_id <> blocked_task_id', name='ck_blocking_tasks_no_self_block'),
    sa.ForeignKeyConstraint(['blocked_task_id'], ['tasks.task_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['blocking_task_id'], ['tasks.task_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('blocking_task_id', 'blocked_task_id')
    )
    op.create_table('task_labels',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('label_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['label_id'], ['labels.label_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'label_id')
    )
    op.create_table('task_shares',
    sa.Column('shared_task_id', sa.Integer(), nullable=False),
    sa.Column('shared_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['shared_task_id'], ['tasks.task_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shared_user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('shared_task_id', 'shared_user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_shares')
    op.drop_table('task_labels')
    op.drop_table('blocking_tasks')
    op.drop_index(op.f('ix_labels_user_id'), table_name='labels')
    op.drop_index(op.f('ix_labels_label_name'), table_name='labels')
    op.drop_table('labels')
    op.drop_index(op.f('ix_friendships_status'), table_name='friendships')
    op.drop_table('friendships')
    # ### end Alembic commands ###
    # Same as the first migration: Postgres keeps the ENUM type after its table
    # is dropped, so re-running upgrade would fail with 'type already exists'.
    sa.Enum(name='friendshipstatus').drop(op.get_bind())
