"""make task_info nullable

Revision ID: 7e1c0ee3ac3b
Revises: 526e9957529d
Create Date: 2026-08-03 14:03:55.191985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e1c0ee3ac3b'
down_revision: Union[str, Sequence[str], None] = '526e9957529d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'task_info',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'task_info',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
