"""add unique constraint on label name per user

Revision ID: b0b73605edef
Revises: 2d01b63b0cdb
Create Date: 2026-08-25 14:22:47.193247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0b73605edef'
down_revision: Union[str, Sequence[str], None] = '2d01b63b0cdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_labels_user_id_label_name', 'labels', ['user_id', 'label_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_labels_user_id_label_name', 'labels', type_='unique')
    # ### end Alembic commands ###
